spring.application.name=Cultoura
# --------------------------
# Server Configuration
# --------------------------
server.port=8080
#and other sensitive information

# --------------------------
# Spring Security OAuth2 Resource Server (Optional)
# If you are configuring a resource server with JWT validation, uncomment and set your JWK Set URI.
# --------------------------
# spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://example.com/.well-known/jwks.json
